# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cyber/proto/qos_profile.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cyber/proto/qos_profile.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x63yber/proto/qos_profile.proto\x12\x12\x61pollo.cyber.proto\"\x9f\x02\n\nQosProfile\x12H\n\x07history\x18\x01 \x01(\x0e\x32$.apollo.cyber.proto.QosHistoryPolicy:\x11HISTORY_KEEP_LAST\x12\x10\n\x05\x64\x65pth\x18\x02 \x01(\r:\x01\x31\x12\x0e\n\x03mps\x18\x03 \x01(\r:\x01\x30\x12S\n\x0breliability\x18\x04 \x01(\x0e\x32(.apollo.cyber.proto.QosReliabilityPolicy:\x14RELIABILITY_RELIABLE\x12P\n\ndurability\x18\x05 \x01(\x0e\x32\'.apollo.cyber.proto.QosDurabilityPolicy:\x13\x44URABILITY_VOLATILE*[\n\x10QosHistoryPolicy\x12\x1a\n\x16HISTORY_SYSTEM_DEFAULT\x10\x00\x12\x15\n\x11HISTORY_KEEP_LAST\x10\x01\x12\x14\n\x10HISTORY_KEEP_ALL\x10\x02*m\n\x14QosReliabilityPolicy\x12\x1e\n\x1aRELIABILITY_SYSTEM_DEFAULT\x10\x00\x12\x18\n\x14RELIABILITY_RELIABLE\x10\x01\x12\x1b\n\x17RELIABILITY_BEST_EFFORT\x10\x02*m\n\x13QosDurabilityPolicy\x12\x1d\n\x19\x44URABILITY_SYSTEM_DEFAULT\x10\x00\x12\x1e\n\x1a\x44URABILITY_TRANSIENT_LOCAL\x10\x01\x12\x17\n\x13\x44URABILITY_VOLATILE\x10\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cyber.proto.qos_profile_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QOSHISTORYPOLICY']._serialized_start=343
  _globals['_QOSHISTORYPOLICY']._serialized_end=434
  _globals['_QOSRELIABILITYPOLICY']._serialized_start=436
  _globals['_QOSRELIABILITYPOLICY']._serialized_end=545
  _globals['_QOSDURABILITYPOLICY']._serialized_start=547
  _globals['_QOSDURABILITYPOLICY']._serialized_end=656
  _globals['_QOSPROFILE']._serialized_start=54
  _globals['_QOSPROFILE']._serialized_end=341
# @@protoc_insertion_point(module_scope)
