# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: modules/common_msgs/control_msgs/pad_msg.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'modules/common_msgs/control_msgs/pad_msg.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from modules.common_msgs.basic_msgs import header_pb2 as modules_dot_common__msgs_dot_basic__msgs_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.modules/common_msgs/control_msgs/pad_msg.proto\x12\x0e\x61pollo.control\x1a+modules/common_msgs/basic_msgs/header.proto\"b\n\nPadMessage\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.apollo.common.Header\x12-\n\x06\x61\x63tion\x18\x02 \x01(\x0e\x32\x1d.apollo.control.DrivingAction*2\n\rDrivingAction\x12\t\n\x05START\x10\x01\x12\t\n\x05RESET\x10\x02\x12\x0b\n\x07VIN_REQ\x10\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'modules.common_msgs.control_msgs.pad_msg_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DRIVINGACTION']._serialized_start=211
  _globals['_DRIVINGACTION']._serialized_end=261
  _globals['_PADMESSAGE']._serialized_start=111
  _globals['_PADMESSAGE']._serialized_end=209
# @@protoc_insertion_point(module_scope)
