# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: modules/common_msgs/routing_msgs/geometry.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'modules/common_msgs/routing_msgs/geometry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from modules.common_msgs.basic_msgs import geometry_pb2 as modules_dot_common__msgs_dot_basic__msgs_dot_geometry__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/modules/common_msgs/routing_msgs/geometry.proto\x12\x0e\x61pollo.routing\x1a-modules/common_msgs/basic_msgs/geometry.proto\"]\n\x0cLaneWaypoint\x12\n\n\x02id\x18\x01 \x01(\t\x12\t\n\x01s\x18\x02 \x01(\x01\x12%\n\x04pose\x18\x03 \x01(\x0b\x32\x17.apollo.common.PointENU\x12\x0f\n\x07heading\x18\x04 \x01(\x01\"9\n\x0bLaneSegment\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07start_s\x18\x02 \x01(\x01\x12\r\n\x05\x65nd_s\x18\x03 \x01(\x01\"\x1f\n\x0bMeasurement\x12\x10\n\x08\x64istance\x18\x01 \x01(\x01\"\x8c\x01\n\x07Passage\x12,\n\x07segment\x18\x01 \x03(\x0b\x32\x1b.apollo.routing.LaneSegment\x12\x10\n\x08\x63\x61n_exit\x18\x02 \x01(\x08\x12\x41\n\x10\x63hange_lane_type\x18\x03 \x01(\x0e\x32\x1e.apollo.routing.ChangeLaneType:\x07\x46ORWARD\"C\n\x0bRoadSegment\x12\n\n\x02id\x18\x01 \x01(\t\x12(\n\x07passage\x18\x02 \x03(\x0b\x32\x17.apollo.routing.Passage*H\n\x12\x44\x65\x61\x64\x45ndRoutingType\x12\x11\n\rROUTING_OTHER\x10\x00\x12\x0e\n\nROUTING_IN\x10\x01\x12\x0f\n\x0bROUTING_OUT\x10\x02*2\n\x0e\x43hangeLaneType\x12\x0b\n\x07\x46ORWARD\x10\x00\x12\x08\n\x04LEFT\x10\x01\x12\t\n\x05RIGHT\x10\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'modules.common_msgs.routing_msgs.geometry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DEADENDROUTINGTYPE']._serialized_start=513
  _globals['_DEADENDROUTINGTYPE']._serialized_end=585
  _globals['_CHANGELANETYPE']._serialized_start=587
  _globals['_CHANGELANETYPE']._serialized_end=637
  _globals['_LANEWAYPOINT']._serialized_start=114
  _globals['_LANEWAYPOINT']._serialized_end=207
  _globals['_LANESEGMENT']._serialized_start=209
  _globals['_LANESEGMENT']._serialized_end=266
  _globals['_MEASUREMENT']._serialized_start=268
  _globals['_MEASUREMENT']._serialized_end=299
  _globals['_PASSAGE']._serialized_start=302
  _globals['_PASSAGE']._serialized_end=442
  _globals['_ROADSEGMENT']._serialized_start=444
  _globals['_ROADSEGMENT']._serialized_end=511
# @@protoc_insertion_point(module_scope)
