# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: modules/common_msgs/routing_msgs/poi.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'modules/common_msgs/routing_msgs/poi.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from modules.common_msgs.map_msgs import map_geometry_pb2 as modules_dot_common__msgs_dot_map__msgs_dot_map__geometry__pb2
from modules.common_msgs.basic_msgs import geometry_pb2 as modules_dot_common__msgs_dot_basic__msgs_dot_geometry__pb2
from modules.common_msgs.routing_msgs import geometry_pb2 as modules_dot_common__msgs_dot_routing__msgs_dot_geometry__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*modules/common_msgs/routing_msgs/poi.proto\x12\x0e\x61pollo.routing\x1a/modules/common_msgs/map_msgs/map_geometry.proto\x1a-modules/common_msgs/basic_msgs/geometry.proto\x1a/modules/common_msgs/routing_msgs/geometry.proto\"\xc2\x01\n\x0bParkingInfo\x12\x18\n\x10parking_space_id\x18\x01 \x01(\t\x12.\n\rparking_point\x18\x02 \x01(\x0b\x32\x17.apollo.common.PointENU\x12<\n\x12parking_space_type\x18\x03 \x01(\x0e\x32 .apollo.routing.ParkingSpaceType\x12+\n\x0c\x63orner_point\x18\x04 \x01(\x0b\x32\x15.apollo.hdmap.Polygon\"\xaf\x01\n\x08Landmark\x12\x0c\n\x04name\x18\x01 \x01(\t\x12.\n\x08waypoint\x18\x02 \x03(\x0b\x32\x1c.apollo.routing.LaneWaypoint\x12\x1c\n\x10parking_space_id\x18\x03 \x01(\tB\x02\x18\x01\x12\x31\n\x0cparking_info\x18\x04 \x01(\x0b\x32\x1b.apollo.routing.ParkingInfo\x12\x14\n\x0c\x63ycle_number\x18\x05 \x01(\x05\"1\n\x03POI\x12*\n\x08landmark\x18\x01 \x03(\x0b\x32\x18.apollo.routing.Landmark*;\n\x10ParkingSpaceType\x12\x11\n\rVERTICAL_PLOT\x10\x00\x12\x14\n\x10PARALLEL_PARKING\x10\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'modules.common_msgs.routing_msgs.poi_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LANDMARK'].fields_by_name['parking_space_id']._loaded_options = None
  _globals['_LANDMARK'].fields_by_name['parking_space_id']._serialized_options = b'\030\001'
  _globals['_PARKINGSPACETYPE']._serialized_start=633
  _globals['_PARKINGSPACETYPE']._serialized_end=692
  _globals['_PARKINGINFO']._serialized_start=208
  _globals['_PARKINGINFO']._serialized_end=402
  _globals['_LANDMARK']._serialized_start=405
  _globals['_LANDMARK']._serialized_end=580
  _globals['_POI']._serialized_start=582
  _globals['_POI']._serialized_end=631
# @@protoc_insertion_point(module_scope)
